# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lz2X3EBmkZV7-rdfvFEuzAbCMtKxPNW_
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5])
y=np.array([4,1,8,1.5,6,2,9,3,7.5,0,5,3.5,9,1.25,4,4,4,4])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y,marker ='o',ms=15)
mec='r'
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x1 = np.array([1,2,3,4])
y1 = np.array([4,9,2,11])
x2 = np.array([1,2,3,4])
y2 = np.array([7,3,8,12])
plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([1,2,3,4,5,6])
y = np.array([1,9,13,21,26,39])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([3,4,5,6,7,8])
y = np.array([3,5,11,4,17,10])
plt.scatter(x,y,color='black')
x = np.array([14,8,10,13,10,5])
y = np.array([7,8,5,9,19,21])
plt.scatter(x,y,color='red')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
mycolor=['black','green','purple', 'lime','aqua','red']
plt.scatter(x,y,color= mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
# Removing the extra space before 'yellow' in the color list
mycolor=['red','green','purple', 'lime','aqua','yellow']
size=[10,30,50,60,120,250]
plt.scatter(x,y,color= mycolor, s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([0,1,2,3,4,5])
y = np.array([0,2,8,1,14,7])
# Removing the extra space before 'yellow' in the color list
mycolor=['red','green','purple', 'lime','aqua','yellow']
size=[10,30,50,60,120,250]
plt.scatter(x,y,color= mycolor, s=size, alpha=0.5)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array(['613','614','615','681'])
y = np.array([25,8,26,40])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas",
"Cherries", "Dates"]
plt.pie(y, labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries",
"Dates"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels,
startangle=90, explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
mycolors = ["#ff63b7", "#ffa500", "b", "#4CAF50"]
myexplode = [0.2, 0, 0, 0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode, colors= mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([3,25,75,15])
mylabels = ["hisob", "suniy intilkt", " falsafa ",
"kibrhafsizlik"]
plt.pie(y, labels=mylabels)
plt.legend()
plt.show()